/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TreeLevel = IDL.Nat;
export const LevelCommission = IDL.Record({
  'levelPercentage' : IDL.Nat,
  'totalLevelEarnings' : IDL.Nat,
  'level' : TreeLevel,
  'levelMembers' : IDL.Nat,
  'commissionAmount' : IDL.Nat,
});
export const MemberId = IDL.Nat;
export const UserProfile = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
});
export const Time = IDL.Int;
export const MatrixPosition = IDL.Nat;
export const MLMTreePosition = IDL.Record({
  'memberId' : MemberId,
  'level' : TreeLevel,
  'position' : MatrixPosition,
});
export const MemberPublic = IDL.Record({
  'id' : IDL.Nat,
  'isCancelled' : IDL.Bool,
  'contactInfo' : IDL.Text,
  'uplineId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'sponsorId' : IDL.Opt(IDL.Nat),
  'membershipDeadline' : Time,
  'feeRefunded' : IDL.Bool,
  'directDownlines' : IDL.Vec(MemberId),
  'registrationTimestamp' : Time,
  'memberIdStr' : IDL.Text,
  'joiningFeePaid' : IDL.Bool,
  'matrixPosition' : MLMTreePosition,
});
export const MemberRegistration = IDL.Record({
  'contactInfo' : IDL.Text,
  'uplineId' : IDL.Opt(MemberId),
  'name' : IDL.Text,
  'sponsorId' : IDL.Opt(MemberId),
});
export const MemberRegistrationResult = IDL.Record({
  'id' : MemberId,
  'memberId' : IDL.Text,
});

export const TradingUser = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'passwordHash' : IDL.Text,
  'aadhaar' : IDL.Text,
  'pan' : IDL.Text,
  'digilockerRef' : IDL.Text,
  'paymentProof' : IDL.Text,
  'selfie' : IDL.Text,
  'kycStatus' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'accountStatus' : IDL.Text,
  'virtualBalance' : IDL.Nat,
  'watchlist' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'referredBy' : IDL.Opt(IDL.Text),
  'referralBonus' : IDL.Nat,
  'esignature' : IDL.Text,
  'tcSigned' : IDL.Bool,
});
export const TradingRegisterResult = IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text });
export const TradingUpdateResult = IDL.Record({ 'ok' : IDL.Bool });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateCommissions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LevelCommission)],
      ['query'],
    ),
  'checkMembershipStatuses' : IDL.Func([], [], []),
  'deleteMember' : IDL.Func([MemberId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMember' : IDL.Func([MemberId], [IDL.Opt(MemberPublic)], ['query']),
  'getMemberRegistrationData' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getSenderDownlines' : IDL.Func([MemberId], [IDL.Vec(MemberId)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMembersByName' : IDL.Func([], [IDL.Vec(MemberPublic)], ['query']),
  'markJoiningFeePaid' : IDL.Func([MemberId], [], []),
  'registerMember' : IDL.Func(
      [MemberRegistration],
      [MemberRegistrationResult],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'registerTradingUser' : IDL.Func([TradingUser], [TradingRegisterResult], []),
  'getTradingUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(TradingUser)], ['query']),
  'getAllTradingUsers' : IDL.Func([], [IDL.Vec(TradingUser)], ['query']),
  'updateTradingUser' : IDL.Func([TradingUser], [TradingUpdateResult], []),
  'updateTradingUserById' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [TradingUpdateResult], []),
  'creditTradingReferralBonus' : IDL.Func([IDL.Text], [TradingUpdateResult], []),
  'nextTradingMemberId' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TreeLevel = IDL.Nat;
  const LevelCommission = IDL.Record({
    'levelPercentage' : IDL.Nat,
    'totalLevelEarnings' : IDL.Nat,
    'level' : TreeLevel,
    'levelMembers' : IDL.Nat,
    'commissionAmount' : IDL.Nat,
  });
  const MemberId = IDL.Nat;
  const UserProfile = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
  });
  const Time = IDL.Int;
  const MatrixPosition = IDL.Nat;
  const MLMTreePosition = IDL.Record({
    'memberId' : MemberId,
    'level' : TreeLevel,
    'position' : MatrixPosition,
  });
  const MemberPublic = IDL.Record({
    'id' : IDL.Nat,
    'isCancelled' : IDL.Bool,
    'contactInfo' : IDL.Text,
    'uplineId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'sponsorId' : IDL.Opt(IDL.Nat),
    'membershipDeadline' : Time,
    'feeRefunded' : IDL.Bool,
    'directDownlines' : IDL.Vec(MemberId),
    'registrationTimestamp' : Time,
    'memberIdStr' : IDL.Text,
    'joiningFeePaid' : IDL.Bool,
    'matrixPosition' : MLMTreePosition,
  });
  const MemberRegistration = IDL.Record({
    'contactInfo' : IDL.Text,
    'uplineId' : IDL.Opt(MemberId),
    'name' : IDL.Text,
    'sponsorId' : IDL.Opt(MemberId),
  });
  const MemberRegistrationResult = IDL.Record({
    'id' : MemberId,
    'memberId' : IDL.Text,
  });
  const TradingUser = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'passwordHash' : IDL.Text,
    'aadhaar' : IDL.Text,
    'pan' : IDL.Text,
    'digilockerRef' : IDL.Text,
    'paymentProof' : IDL.Text,
    'selfie' : IDL.Text,
    'kycStatus' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'accountStatus' : IDL.Text,
    'virtualBalance' : IDL.Nat,
    'watchlist' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'referredBy' : IDL.Opt(IDL.Text),
    'referralBonus' : IDL.Nat,
    'esignature' : IDL.Text,
    'tcSigned' : IDL.Bool,
  });
  const TradingRegisterResult = IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text });
  const TradingUpdateResult = IDL.Record({ 'ok' : IDL.Bool });

  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateCommissions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LevelCommission)],
        ['query'],
      ),
    'checkMembershipStatuses' : IDL.Func([], [], []),
    'deleteMember' : IDL.Func([MemberId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMember' : IDL.Func([MemberId], [IDL.Opt(MemberPublic)], ['query']),
    'getMemberRegistrationData' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getSenderDownlines' : IDL.Func([MemberId], [IDL.Vec(MemberId)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMembersByName' : IDL.Func([], [IDL.Vec(MemberPublic)], ['query']),
    'markJoiningFeePaid' : IDL.Func([MemberId], [], []),
    'registerMember' : IDL.Func(
        [MemberRegistration],
        [MemberRegistrationResult],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'registerTradingUser' : IDL.Func([TradingUser], [TradingRegisterResult], []),
    'getTradingUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(TradingUser)], ['query']),
    'getAllTradingUsers' : IDL.Func([], [IDL.Vec(TradingUser)], ['query']),
    'updateTradingUser' : IDL.Func([TradingUser], [TradingUpdateResult], []),
    'updateTradingUserById' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [TradingUpdateResult], []),
    'creditTradingReferralBonus' : IDL.Func([IDL.Text], [TradingUpdateResult], []),
    'nextTradingMemberId' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
