/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LevelCommission {
  'levelPercentage' : bigint,
  'totalLevelEarnings' : bigint,
  'level' : TreeLevel,
  'levelMembers' : bigint,
  'commissionAmount' : bigint,
}
export interface MLMTreePosition {
  'memberId' : MemberId,
  'level' : TreeLevel,
  'position' : MatrixPosition,
}
export type MatrixPosition = bigint;
export type MemberId = bigint;
export interface MemberPublic {
  'id' : bigint,
  'isCancelled' : boolean,
  'contactInfo' : string,
  'uplineId' : [] | [bigint],
  'name' : string,
  'sponsorId' : [] | [bigint],
  'membershipDeadline' : Time,
  'feeRefunded' : boolean,
  'directDownlines' : Array<MemberId>,
  'registrationTimestamp' : Time,
  'memberIdStr' : string,
  'joiningFeePaid' : boolean,
  'matrixPosition' : MLMTreePosition,
}
export interface MemberRegistration {
  'contactInfo' : string,
  'uplineId' : [] | [MemberId],
  'name' : string,
  'sponsorId' : [] | [MemberId],
}
export interface MemberRegistrationResult {
  'id' : MemberId,
  'memberId' : string,
}
export type Time = bigint;
export type TreeLevel = bigint;
export interface UserProfile { 'contactInfo' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateCommissions' : ActorMethod<[bigint], Array<LevelCommission>>,
  'checkMembershipStatuses' : ActorMethod<[], undefined>,
  'deleteMember' : ActorMethod<[MemberId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMember' : ActorMethod<[MemberId], [] | [MemberPublic]>,
  'getMemberRegistrationData' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getSenderDownlines' : ActorMethod<[MemberId], Array<MemberId>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMembersByName' : ActorMethod<[], Array<MemberPublic>>,
  'markJoiningFeePaid' : ActorMethod<[MemberId], undefined>,
  'registerMember' : ActorMethod<
    [MemberRegistration],
    MemberRegistrationResult
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];