/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
});
export const MemberId = IDL.Nat;
export const Time = IDL.Int;
export const TreeLevel = IDL.Nat;
export const MLMTreePosition = IDL.Record({
  'memberId' : MemberId,
  'level' : TreeLevel,
  'position' : IDL.Nat,
});
export const MemberPublic = IDL.Record({
  'id' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'sponsorId' : IDL.Opt(IDL.Nat),
  'feeRefunded' : IDL.Bool,
  'directDownlines' : IDL.Vec(MemberId),
  'registrationTimestamp' : Time,
  'joiningFeePaid' : IDL.Bool,
  'matrixPosition' : MLMTreePosition,
});
export const MemberRegistration = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'sponsorId' : IDL.Opt(MemberId),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMember' : IDL.Func([MemberId], [IDL.Opt(MemberPublic)], ['query']),
  'getSenderDownlines' : IDL.Func([MemberId], [IDL.Vec(MemberId)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMembersByName' : IDL.Func([], [IDL.Vec(MemberPublic)], ['query']),
  'markJoiningFeePaid' : IDL.Func([MemberId], [], []),
  'registerMember' : IDL.Func([MemberRegistration], [MemberId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
  });
  const MemberId = IDL.Nat;
  const Time = IDL.Int;
  const TreeLevel = IDL.Nat;
  const MLMTreePosition = IDL.Record({
    'memberId' : MemberId,
    'level' : TreeLevel,
    'position' : IDL.Nat,
  });
  const MemberPublic = IDL.Record({
    'id' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'sponsorId' : IDL.Opt(IDL.Nat),
    'feeRefunded' : IDL.Bool,
    'directDownlines' : IDL.Vec(MemberId),
    'registrationTimestamp' : Time,
    'joiningFeePaid' : IDL.Bool,
    'matrixPosition' : MLMTreePosition,
  });
  const MemberRegistration = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'sponsorId' : IDL.Opt(MemberId),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMember' : IDL.Func([MemberId], [IDL.Opt(MemberPublic)], ['query']),
    'getSenderDownlines' : IDL.Func([MemberId], [IDL.Vec(MemberId)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMembersByName' : IDL.Func([], [IDL.Vec(MemberPublic)], ['query']),
    'markJoiningFeePaid' : IDL.Func([MemberId], [], []),
    'registerMember' : IDL.Func([MemberRegistration], [MemberId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };